### PR TITLE
Remove labs/lab06/data links

### PR DESCRIPTION
**Pull request by adeet1**
Fix broken links to directory labs/lab06/data, as suggested by @50Wliu

### CODE REVIEW

**Comment by adeet1** [comment]
@50Wliu When I run `make` on my end, pandoc messes up the font of all of the HTML files and changes them to a Times New Roman-like font instead of preserving the Markdown font that the website is currently written in.

How do I fix this problem?

**Comment by 50Wliu** [comment]
> How do I fix this problem?

I am trying to fix this by creating a GitHub Action to automatically run `make all` on pushes to master :).

In the meantime, what pandoc version (`pandoc --version`) and OS are you running on?

**Comment by adeet1** [comment]
> > How do I fix this problem?
> 
> I am trying to fix this by creating a GitHub Action to automatically run `make all` on pushes to master :).
> 
> In the meantime, what pandoc version (`pandoc --version`) and OS are you running on?

I'm using version 2.9.1.1.

**Comment by 50Wliu** [comment]
Uh, maybe try 1.19.2.4? That's the last version before 2.0 and is the one I'm using, coincidentally.

**Comment by adeet1** [comment]
I downloaded the .tar.gz file for pandoc 1.19.2.4 from [here](https://github.com/jgm/pandoc/releases?after=2.0.3), and installed stack (perhaps it is a dependency) via `sudo apt install haskell-stack`. But when I call `make`, I get the following error:
```
No compiler found, expected minor version match with ghc-8.0.2 (x86_64-nopie) (based on resolver setting in /home/student/pandoc-1.19.2.4/stack.yaml).
To install the correct GHC into /home/student/.stack/programs/x86_64-linux/, try running "stack setup" or use the "--install-ghc" flag.
Makefile:5: recipe for target 'quick' failed
make: *** [quick] Error 1
```

**Comment by 50Wliu** [comment]
Try `sudo apt install pandoc=1.19.2.4`

**Comment by adeet1** [comment]
Yes, that worked! Thank you so much!

**Comment by 50Wliu** [comment]
Well, looks like we'll have work to do when Ubuntu starts shipping with Pandoc 2.x, then 😬

**Pull request merged**
